# docker-compose.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: builder
    container_name: shorturl-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
    container_name: shorturl-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    command: npm run dev
